extension=odbc.so
extension=pdo_odbc.so
[ODBC]
odbc.allow_persistent = On
odbc.check_persistent = On
odbc.default_cursortype = Static cursor
odbc.defaultbinmode = 1
odbc.defaultlrl = 4096
odbc.max_links = -1
odbc.max_persistent = -1
