services:
  front:
    container_name: ${PROJECT_NAME}_dev_front
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - URL_BACK=${URL_BACK}
    ports:
      - "${FRONT_PORT}:3000"
    volumes:
      - ./front:/app/front
      - /app/front/node_modules

  back:
    container_name: ${PROJECT_NAME}_dev_back
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/var/www/html
      - ./back/vendor:/var/www/html/vendor      # ← vendors visibles côté Mac
    ports:
      - "${BACK_PORT}:8000"
    restart: always
    environment:
      APP_ENV: dev
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}
      weatherApiKey: ${weatherApiKey}
      weatherApiFreeVersion: ${weatherApiFreeVersion}
      savKey: ${savKey}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
    depends_on:
      - db
      - php-fpm

  php-fpm:
    container_name: ${PROJECT_NAME}_dev_phpfpm
    build:
      context: ./php-fpm
    volumes:
      - ./back:/var/www/html
      - ./back/vendor:/var/www/html/vendor      # ← même vendors que le back
    environment:
      APP_ENV: dev
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}
      weatherApiKey: ${weatherApiKey}
      weatherApiFreeVersion: ${weatherApiFreeVersion}
      savKey: ${savKey}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
    depends_on:
      - db

  db:
    container_name: ${PROJECT_NAME}_dev_db
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: ${PROJECT_NAME}_dev_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db

  nginx:
    container_name: ${PROJECT_NAME}_dev_nginx
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./back:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

volumes:
  db_data:
