# Build stage
FROM node:18 as build

WORKDIR /app/front

COPY package*.json ./
RUN npm install

COPY . .
ENV NODE_OPTIONS="--openssl-legacy-provider"
ARG URL_BACK
ENV URL_BACK=$URL_BACK
RUN npm run generate

# Production stage (serve static files via nginx)
FROM nginx:alpine
COPY --from=build /app/front/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
